### ISSUE TITLE
sparta::CircularBuffer doesn't collapse empty entries

### ISSUE THREAD

**Issue by shuzhih** [sparcians/map#443] opened 2023-09-20 16:55 UTC

**Comment by shuzhih** [comment] 2023-09-20 19:22
Was going to update the test. Assigning it to me.

**Comment by shuzhih** [comment] 2023-09-21 14:55
```
diff --git a/sparta/test/CircularBuffer/CircularBuffer_test.cpp b/sparta/test/CircularBuffer/CircularBuffer_test.cpp
index 2abbb19f..ed0411c4 100644
--- a/sparta/test/CircularBuffer/CircularBuffer_test.cpp
+++ b/sparta/test/CircularBuffer/CircularBuffer_test.cpp
@@ -429,6 +429,27 @@ void testEraseInsert()
     EXPECT_FALSE(rcbit.isValid());
     EXPECT_FALSE(rbit.isValid());
 
+    for(uint32_t i = 0; i < BUF_SIZE; ++i) {
+        cir_buffer.push_back(i);
+    }
+    EXPECT_EQUAL(cir_buffer.size(), BUF_SIZE);
+    sparta::CircularBuffer<uint32_t>::iterator it = cir_buffer.begin();
+    EXPECT_TRUE(it.isValid());
+    const uint32_t BUF_MID_POINT = BUF_SIZE / 2;
+    for(uint32_t i = 0; i < BUF_MID_POINT; ++i) {
+        ++it;
+        EXPECT_TRUE(it.isValid());
+    }
+    cir_buffer.erase(it);
+    EXPECT_FALSE(it.isValid());
+    it = cir_buffer.begin();
+    EXPECT_TRUE(it.isValid());
+    while (it != cir_buffer.end()) {
+        ++it;
+        EXPECT_TRUE(it.isValid());
+    }
+    cir_buffer.clear();
+
     // Test insert
     auto nit = cir_buffer.insert(cir_buffer.begin(), 1);
     EXPECT_EQUAL(cir_buffer.size(), 1);

```
Failed signature
```
tart testing: Sep 21 07:44 PDT
----------------------------------------------------------
1/2 Testing: CircularBuffer_test
1/2 Test: CircularBuffer_test
Command: "/nfs/teams/perf/dc-scratch/users/shou/map/sparta/Release/test/CircularBuffer/CircularBuffer_test" "CircularBuffer_test_RUN"
Directory: /nfs/teams/perf/dc-scratch/users/shou/map/sparta/Release/test/CircularBuffer
"CircularBuffer_test" start time: Sep 21 07:44 PDT
Output:
----------------------------------------------------------
The value: 1
Test 'it.isValid()' FAILED on line 449 in file /nfs/teams/perf/dc-scratch/users/shou/map/sparta/test/CircularBuffer/CircularBuffer_test.cpp

```

**Comment by knute-sifive** [comment] 2023-09-21 16:06
Thanks, I'll take a look

**Comment by knute-sifive** [comment] 2023-09-21 20:04
Interesting -- the buffer is collapsing, but the end iterator is odd.  In fact, it looks like iteration is just wacky.  

This works, BTW, no issues with `isValid` and shows the correct counts.  🤷🏻‍♂️ .  More debugging...
```
    for (auto val : cir_buffer) {
        std::cout << val << std::endl;
    }

```

**Comment by knute-sifive** [comment] 2023-09-21 23:06
Wait, you have a bug in the test!

This is wrong:
```
    while (it != cir_buffer.end()) {
        ++it;
        EXPECT_TRUE(it.isValid());
    }
```
It should be:
```
    while (it != cir_buffer.end()) {
        EXPECT_TRUE(it.isValid());
        ++it;
    }
```
With this fix, the test passes.

**Comment by shuzhih** [comment] 2023-09-21 23:11
Sorry!

**Comment by klingaard** [comment] 2023-10-24 22:51
Hey @shuzhih were you able to reproduce this issue?

**Comment by shuzhih** [comment] 2023-10-25 15:27
Unfortunately. Passed it along to team member. It was over a month ago.

**Comment by knute-sifive** [comment] 2023-10-25 15:28
I'm going to close this until its reproduced again.

**Closed by knute-sifive** 2023-10-25 15:28 UTC
Labels: bug, component: sparta
